### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by flo-wolf** [colgreen/sharpneat-refactor#4]
Hello :) 
I am planning to use sharpneat in a project I am working on for my bachelor thesis, though I am unsure whether the refactored repo is already production ready. I wasn't able to find any information regarding the state of this repository, only the pointer towards it from the original sharpneat repo.

Do you reccomend using it as it is?

Awesome project, keep it up!

**Comment by mattcolefla** [comment]
Hi Florian,

 

Not sure if this message is for me or Colin. The last I knew the refactored version was still not ready for production, but I’ll let Colin comment as, of course, he knows better. 

 

Kind Regards,

Matt R. Cole

 <http://www.evolvedaisolutions.com/> www.evolvedaisolutions.com

 <https://www.linkedin.com/in/evolvedai/> https://www.linkedin.com/in/evolvedai/

**Comment by colgreen** [comment]
Hi,

I recommend you use the sharpneat-refactor branch for a new project. All of the core functionality is in place and tested; right now I am porting and rewriting the windows UI 'layer' over the core code, so I was waiting until some of that UI code was ready before making it an official release.

If it helps sway your decision.. if you do encounter any missing pieces then I can help out.

Colin

**Comment by flo-wolf** [comment]
Thank you both for the fast reply!
I will only need the core code, since I am planning to use it inside Unity3D, maybe with CPPN adaption. There is already an integration of shaptneat out there, but with the old code base: [UnityNEAT](https://github.com/lordjesus/UnityNEAT). I am thinking about writing an integration with the refactored core, in hope to make use of your refactoring work with a more streamlined and optimized NEAT implementation. 

I will keep you updated and provide you with proper credit and the repo link as soon as I have produced something

Florian

**Comment by flo-wolf** [comment]
Edit: I just realized, @colgreen you contributed to the UnityNEAT project! In that case I might just fork it to include the changes to the core that happened during the last 14 months

**Comment by colgreen** [comment]
My pull request to UnityNEAT was just to bring in some fixes from the sharpneat master branch; it's all still the old code base. 

Also, bear in mind that sharpneat-refactor doesn't have CPPNs / HyperNEAT yet.

**Comment by flo-wolf** [comment]
Okay, that is good to know. In that case I will probably stick to the current UnityNEAT repo (which luckily works just fine) and do an update as soon as there is CPPN support in the refactored version.

Thanks for the heads up!
