### ISSUE TITLE
Redzen from 12.0.0-preview1

### ISSUE THREAD

**Issue by TheBreadmanWalking** [colgreen/sharpneat-refactor#6]
requesting this package but it does not seem to yet be released

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Redzen with version (>= 12.0.0-preview1)
  - Found 27 version(s) in nuget.org [ Nearest version: 11.0.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
 refactor\src\Tests\SharpNeat.Tasks.Tests\SharpNeat.Tasks.Tests.csproj	1

**Comment by colgreen** [comment]
For a quick workaround, you can unzip the attached nuget package file to a local folder. 

Then add hat folder as a package source in Visual Studio (VS supports using a local folder as a package feed/source). You can add the feed here:

   Visual Studio -> options -> NuGet Package manager -> Package Sources

[Redzen.12.0.0-preview1.nupkg.zip](https://github.com/colgreen/sharpneat-refactor/files/5811400/Redzen.12.0.0-preview1.nupkg.zip)

Hope that helps.  The stable v12 package will be released soon. I prefer not to publish lots of preview builds to nuget.org.. I guess I should set up my own public feed to get around this.

**Comment by TheBreadmanWalking** [comment]
ok thank you for super fast replyed. i will try that,

**Comment by TheBreadmanWalking** [comment]
Perfect worked. Great no errors. I did try loading redzen from github first. (referenced project) but that had few things missing still I think,. but thank you.

**Comment by colgreen** [comment]
@TheBreadmanWalking  FYI, redzen 12.0.0.0-preview5 is published to nuget.org, and the sharpneat-refactor repo is updated to use it.
